### ISSUE TITLE
Task 1. Hello world

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#1]
Create folder `script` for python scripts.
Create script `hello_word.py` which will print text "Hello world!" to the console.
This script should be run with the following command:
```
python script/hello_world.py
```

**Comment by AnnaLangner** [comment]
I've already done this task, that was about? It works fine on my console.

wt., 16 cze 2020 o 21:11 Krzysztof Langner <notifications@github.com>
napisał(a):

**Comment by klangner** [comment]
Ok. well done :-)
