### ISSUE TITLE
Task 8. Verify URL

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#14]
Create script `verify_url.py` which will get url as an argument, then get content at given url and return status code.
Use [request](https://requests.readthedocs.io/en/master/) library for accessing web page.

Example:
```sh
verify_url.py https://wikipedia.org
Status code: 200 
```

**Comment by AnnaLangner** [comment]
"Request" does not work on my computer.
I have Python 3.8.3, on the "Request" pages there is information:
`Requests officially supports Python 2.7 & 3.4–3.7, and runs great on PyPy.`
Should I change my Python version?

**Comment by klangner** [comment]
Well done
