### ISSUE TITLE
Task 9. Find on page

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#17]
Write python script which will take as an input url to the page and text.
The script should fetch the content of the page and find the text on the page.
If the text is found then print fragment of  the page which starts 10 characters before found text and 10 characters after it.
If not found then print "Text '<text>' not found"

**Comment by AnnaLangner** [comment]
I added "inputs" and printed the text, but the text only gets the "title" from the page. I don't know why "text" doesn't download another text from the site.

I'm stuck with "print a page fragment that begins 10 characters before the found text and 10 characters after it." Should I use "BeautifulSoup"?

Can I ask for a hint?

**Comment by klangner** [comment]
Which page are you queering? Probably the problem is with the page. Maybe it is generated with javascript. Try any wikipedia page.

At this stage BeautifulSoup is not needed

**Comment by AnnaLangner** [comment]
I tried with wikipedia :(

**Comment by klangner** [comment]
Ok. Lets fix other suggestions first and then I will look at it.

**Comment by klangner** [comment]
When do you get this error?
Please remember that the url should start with the http://

**Comment by klangner** [comment]
Lets merge this and we will fix remaining problems in new task.
