### ISSUE TITLE
Task 2. Hello "name"

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#2]
Please create script which will take one parameter as an input `name` and print "Hello `name`" on the console

**Comment by AnnaLangner** [comment]
I've already done this task.

**Comment by klangner** [comment]
Well done.
As a continuation:
Please modify this script to accept the additional parameter during the run. 
So when you run the program like this:
```sh
python script/hello_name.py Alice
```

It should print:
```
Hello Alice
```

If the parameter is not provided, then use `input` to the ask user about a name like it is working now.
Example:
```
python script/hello_name.py
Whats Your name? Bob
Hello Bob
```

**Comment by klangner** [comment]
As a hint:
Look for:
`python command line argument parsing`
on the internet for more help.

**Comment by AnnaLangner** [comment]
changes have been made

**Comment by klangner** [comment]
Looks nice, but :-)

1. Please add 2 empty lines after block of imports. E.g.
```python
import sys
import argparse


print("hello world")
```

2. If the argument is not provided then this script should ask for the name using `input` function like it did before.

**Comment by AnnaLangner** [comment]
I'm not sure if this is correct, but I have no more ideas how to do this task. You can add the additional parameter using  '--name NAME' flag.

**Comment by klangner** [comment]
This is almost correct. Just instead of:
```python
parser.add_argument("--name", help="name the string you are use here")
```
should be:
```python
parser.add_argument("name", help="Please provide the name")
```

**Comment by AnnaLangner** [comment]
When I change `"--name"` to `"name"` an error occurs:  `error : the following arguments are required: name`. 
Name without `--` is no longer an optional argument .

**Comment by klangner** [comment]
I see, you are right.
Let's consider it done then
