### ISSUE TITLE
fetch_content.py cleaning

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#20]
Lets clean a code:
  * [x] Add 2 empty lines between each functions, or between function and global code
  * [x] Rename function `arguments` to `fetch_arguments`. This function should return 2 arguments (url, text)
  * [x] function `add_characters` has wrong name. Think what it is doing and provide better name
  * [x] do not print found text fragments inside function. Return list of fragments instead.
  * [x] You can remove `input` functions. If the arguments are not provided then just print error message.

**Comment by klangner** [comment]
Let's do it step by step

**Comment by AnnaLangner** [comment]
I have almost done

**Comment by klangner** [comment]
Does it work for you?
Even if you do step by step it is important that each step should work.

**Comment by AnnaLangner** [comment]
Now it working

**Comment by klangner** [comment]
Well done. You can merge it now.
