### ISSUE TITLE
Introduction to the Selenium

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#22]
Check Selenium documentation:
https://selenium-python.readthedocs.io

Create script `test_1.py` and implement first example from the page:
https://selenium-python.readthedocs.io/getting-started.html

**Comment by AnnaLangner** [comment]
I made the first example, I received this message `selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".q"}` 
and opened new tab with this site `http: // www.python.org`

Should I do PR for this task?

**Comment by klangner** [comment]
Yes, please do, so I can check it locally.
