### ISSUE TITLE
this is not needed. It was ok before

### ISSUE THREAD

**Issue by AnnaLangner** [AnnaLangner/pysandbox#27]
this is not needed. It was ok before  -> Which line is not needed?

_Originally posted by @klangner in https://github.com/AnnaLangner/pysandbox/pull/26_

But when I wrote this `assert "Unit Testing" in driver.title`  I have a AssertionError in this line

When I wrote this: `search_input.send_keys(Keys.ENTER)` i have this error:

```
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"halting problem"}
  (Session info: chrome=83.0.4103.116)
```
because it does not enter the Unit Tests page

**Comment by klangner** [comment]
I was referring to the print() function.
