### ISSUE TITLE
Create 3 test scenarios

### ISSUE THREAD

**Issue by klangner** [AnnaLangner/pysandbox#31]
Check the following application:
http://todomvc.com/examples/react/#/

Look what is it doing the then propose 3 different testing scenarios as 3 different issue.
This scenarios should have list of actions which should be taken and with the asserts to test the program state.

No code is needed for this task.

**Comment by AnnaLangner** [comment]
Was about something like that?

first scenario "task completed"
1. Go to the website
2. Check if you're on a good website
3. Enter several tasks
4. Check if the "completed" class has been added to the item after selecting the task.

second scenario "clear completed task"
1. Go to the website
2. Check if you're on a good website
3. Enter several tasks
4. Check if you can delete all completed tasks using a "clear-completed" button.

third scenario "switch tabs"
1. Go to the website
2. Check if you're on a good website
3. Enter several tasks
4. Mark the first task as done
5. Check if you can switch between all / active / completed tabs

**Comment by AnnaLangner** [comment]
Test cases is the same as test scenario?

**Comment by klangner** [comment]
Let's focus on the first scenario first.
You need to be more precise in what should be done. So other person following the instructions will exactly know what to do.
So you should have steps like this examples:
* Add task "Buy some fruits"
* Press "Active" button
* Verify that the task "buy some fruits" is on the list
* Verify that "item left label has value 1
* etc.

And yes Test Case is the same as test scenario.

**Comment by AnnaLangner** [comment]
like that? 

first scenario "task completed"
1. Add "task1" and press enter
2. Check if "task1" is active
3. Add "task2" and press enter
4. Check if "task1" is different from "task2"
5. Check that "task2" is active
6. Click "task2" to complete and verify that it has been completed

second scenario "clear completed task"
1. Add "task1", "task2", "task3"
2. Check if "task1", "task2", "task3" are active
3. Click "task1", "task2" to complete
4. Verify if clicking the "clear completed" button will delete all completed tasks

third scenario "switch tabs"
1. Add "task1", "task2", "task3"
2. Check if "task1", "task2", "task3" are active
4. Mark the "task1" as done
5. Check if you can switch between all / active / completed tabs

**Comment by klangner** [comment]
Yes it is much better. Just in use case 1 point 6 for example should be split into 2 steps.

**Comment by AnnaLangner** [comment]
first scenario "task completed"
1. Add "task1" and press enter
2. Check if "task1" is active
3. Add "task2" and press enter
4. Check if "task1" is different from "task2"
5. Check that "task2" is active
6. Click "task2" to complete
7. verify that "task2" has been completed

second scenario "clear completed task"
1. Add "task1", "task2", "task3"
2. Check if "task1", "task2", "task3" are active
3. Click "task1", "task2" to complete
4. Verify if clicking the "clear completed" button will delete all completed tasks

third scenario "switch tabs"
1. Add "task1", "task2", "task3"
2. Check if "task1", "task2", "task3" are active
4. Mark the "task1" as done
5. Check if you can switch between all / active / completed tabs
