### ISSUE TITLE
first scenario "task completed"

### ISSUE THREAD

**Issue by AnnaLangner** [AnnaLangner/pysandbox#32]
first scenario for application:  http://todomvc.com/examples/react/#/

1. Add "task1" and press enter
2. Check if "task1" is active
3. Add "task2" and press enter
4. Check if "task1" is different from "task2"
5. Check that "task2" is active
6. Click "task2" to complete
7. verify that "task2" has been completed

**Comment by AnnaLangner** [comment]
@klangner  When I finish this scenario, should I create a new file with scenario 2 or keep working on scenario_1.py?

**Comment by klangner** [comment]
Create script test_todo.py and put all use cases there.
