### ISSUE TITLE
second scenario "clear completed task"

### ISSUE THREAD

**Issue by AnnaLangner** [AnnaLangner/pysandbox#35]
1. Add "task3"
2. Add "task4"
3. Check if "task3" is active
4. Check if "task4" is active
5. Click "task3" to complete
6. Click buton "clear completed"
7. Verify if clicking the "clear completed" button will delete all completed tasks

**Comment by klangner** [comment]
You need to have 1 action per line.
Add "task3", "task4" are 2 actions

**Comment by klangner** [comment]
BTW It is a good practice to verify all assert before fixing them. So first run code with assert and check that it fails, then add necessary action and check then now assert passes.
Otherwise you can create dummy test which doesn't check the correct assertion.

**Comment by AnnaLangner** [comment]
I'm not sure what to do.  I should use  unittest? Can you give an example of verify assert?
